name: cacao
description: Contact-Confirming Application used at Okayama University.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.3+8

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_hooks: ^0.18.0
  hooks_riverpod: ^2.0.0-dev.5
  freezed: ^2.0.2
  cupertino_icons: ^1.0.2
  hexcolor: ^2.0.4
  flutter_svg: ^1.0.3
  audioplayers: ^0.20.1
  vibration: ^1.7.4-nullsafety.0
  nfc_manager: ^3.1.0
  qr_code_scanner: ^0.7.0
  permission_handler: ^9.2.0
  flutter_dotenv: ^5.0.0
  http: ^0.13.3
  shared_preferences: ^2.0.6
  webview_flutter: ^3.0.2
  connectivity: ^3.0.6
  simple_gradient_text: ^1.2.3
  styled_widget: ^0.4.0+3
  get_it: ^7.2.0
  fluttertoast: ^8.0.9
  json_serializable: ^6.2.0
  mock_web_server: ^5.0.0-nullsafety.1

dev_dependencies:
  build_runner: ^2.1.10
  flutter_launcher_icons: ^0.9.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/sounds/success.mp3

  fonts:
    - family: NotoSansJP
      fonts:
        - asset: assets/fonts/NotoSansJP-Black.otf
          weight: 900
        - asset: assets/fonts/NotoSansJP-Bold.otf
          weight: 700
        - asset: assets/fonts/NotoSansJP-Light.otf
          weight: 500
        - asset: assets/fonts/NotoSansJP-Medium.otf
          weight: 400
        - asset: assets/fonts/NotoSansJP-Regular.otf
          weight: 300
        - asset: assets/fonts/NotoSansJP-Thin.otf
          weight: 100

flutter_icons:
  image_path: "assets/icon.png"
  android: true
  ios: true
  remove_alpha_ios: true